apiVersion: v1
kind: Pod
metadata:
  name: fugaginx
  labels:
    app: fugaginx
spec:
  containers:
  - image: nginx
    name: fugaginx-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: fugaginx
spec:
  selector:
    app: fugaginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fugaginx
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: fugaginx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fugaginx
          servicePort: 80
