apiVersion: v1
kind: Pod
metadata:
  name: hogeginx
  labels:
    app: hogeginx
spec:
  containers:
  - image: httpd
    name: hogeginx-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: hogeginx
spec:
  selector:
    app: hogeginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hogeginx
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: hogeginx.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: hogeginx
          servicePort: 80
